package com.google.android.gms.games.internal.player;

import android.text.TextUtils;

public final class PlayerColumnNames {
    public final String name;
    public final String title;
    public final String zzbcA;
    public final String zzbcB;
    public final String zzbcC;
    public final String zzbcD;
    public final String zzbcE;
    public final String zzbcF;
    public final String zzbcG;
    public final String zzbcH;
    public final String zzbcI;
    public final String zzbcJ;
    public final String zzbcK;
    public final String zzbcL;
    public final String zzbcf;
    public final String zzbcg;
    public final String zzbch;
    public final String zzbci;
    public final String zzbcj;
    public final String zzbck;
    public final String zzbcl;
    public final String zzbcm;
    public final String zzbcn;
    public final String zzbco;
    public final String zzbcp;
    public final String zzbcq;
    public final String zzbcr;
    public final String zzbcs;
    public final String zzbct;
    public final String zzbcu;
    public final String zzbcv;
    public final String zzbcw;
    public final String zzbcx;
    public final String zzbcy;
    public final String zzbcz;

    public PlayerColumnNames(String str) {
        if (TextUtils.isEmpty(str)) {
            this.zzbcf = "external_player_id";
            this.zzbcg = "profile_name";
            this.zzbch = "profile_icon_image_uri";
            this.zzbci = "profile_icon_image_url";
            this.zzbcj = "profile_hi_res_image_uri";
            this.zzbck = "profile_hi_res_image_url";
            this.zzbcl = "last_updated";
            this.zzbcm = "is_in_circles";
            this.zzbcn = "played_with_timestamp";
            this.zzbco = "current_xp_total";
            this.zzbcp = "current_level";
            this.zzbcq = "current_level_min_xp";
            this.zzbcr = "current_level_max_xp";
            this.zzbcs = "next_level";
            this.zzbct = "next_level_max_xp";
            this.zzbcu = "last_level_up_timestamp";
            this.title = "player_title";
            this.zzbcv = "has_all_public_acls";
            this.zzbcw = "is_profile_visible";
            this.zzbcx = "most_recent_external_game_id";
            this.zzbcy = "most_recent_game_name";
            this.zzbcz = "most_recent_activity_timestamp";
            this.zzbcA = "most_recent_game_icon_uri";
            this.zzbcB = "most_recent_game_hi_res_uri";
            this.zzbcC = "most_recent_game_featured_uri";
            this.zzbcD = "has_debug_access";
            this.zzbcE = "gamer_tag";
            this.name = "real_name";
            this.zzbcF = "banner_image_landscape_uri";
            this.zzbcG = "banner_image_landscape_url";
            this.zzbcH = "banner_image_portrait_uri";
            this.zzbcI = "banner_image_portrait_url";
            this.zzbcJ = "gamer_friend_status";
            this.zzbcK = "gamer_friend_update_timestamp";
            this.zzbcL = "is_muted";
            return;
        }
        String valueOf = String.valueOf(str);
        String valueOf2 = String.valueOf("external_player_id");
        this.zzbcf = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("profile_name");
        this.zzbcg = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("profile_icon_image_uri");
        this.zzbch = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("profile_icon_image_url");
        this.zzbci = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("profile_hi_res_image_uri");
        this.zzbcj = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("profile_hi_res_image_url");
        this.zzbck = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("last_updated");
        this.zzbcl = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("is_in_circles");
        this.zzbcm = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("played_with_timestamp");
        this.zzbcn = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("current_xp_total");
        this.zzbco = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("current_level");
        this.zzbcp = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("current_level_min_xp");
        this.zzbcq = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("current_level_max_xp");
        this.zzbcr = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("next_level");
        this.zzbcs = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("next_level_max_xp");
        this.zzbct = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("last_level_up_timestamp");
        this.zzbcu = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("player_title");
        this.title = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("has_all_public_acls");
        this.zzbcv = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("is_profile_visible");
        this.zzbcw = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("most_recent_external_game_id");
        this.zzbcx = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("most_recent_game_name");
        this.zzbcy = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("most_recent_activity_timestamp");
        this.zzbcz = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("most_recent_game_icon_uri");
        this.zzbcA = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("most_recent_game_hi_res_uri");
        this.zzbcB = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("most_recent_game_featured_uri");
        this.zzbcC = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("has_debug_access");
        this.zzbcD = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("gamer_tag");
        this.zzbcE = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("real_name");
        this.name = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("banner_image_landscape_uri");
        this.zzbcF = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("banner_image_landscape_url");
        this.zzbcG = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("banner_image_portrait_uri");
        this.zzbcH = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("banner_image_portrait_url");
        this.zzbcI = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("gamer_friend_status");
        this.zzbcJ = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("gamer_friend_update_timestamp");
        this.zzbcK = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("is_muted");
        this.zzbcL = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
    }
}
