package com.google.android.gms.fitness;

import com.github.paolorotolo.appintro.C0394R;
import com.google.android.gms.games.quest.Quests;

public class FitnessActivities {
    public static final String AEROBICS = "aerobics";
    public static final String ARCHERY = "archery";
    public static final String BADMINTON = "badminton";
    public static final String BASEBALL = "baseball";
    public static final String BASKETBALL = "basketball";
    public static final String BIATHLON = "biathlon";
    public static final String BIKING = "biking";
    public static final String BIKING_HAND = "biking.hand";
    public static final String BIKING_MOUNTAIN = "biking.mountain";
    public static final String BIKING_ROAD = "biking.road";
    public static final String BIKING_SPINNING = "biking.spinning";
    public static final String BIKING_STATIONARY = "biking.stationary";
    public static final String BIKING_UTILITY = "biking.utility";
    public static final String BOXING = "boxing";
    public static final String CALISTHENICS = "calisthenics";
    public static final String CIRCUIT_TRAINING = "circuit_training";
    public static final String CRICKET = "cricket";
    public static final String CROSSFIT = "crossfit";
    public static final String CURLING = "curling";
    public static final String DANCING = "dancing";
    public static final String DIVING = "diving";
    public static final String ELEVATOR = "elevator";
    public static final String ELLIPTICAL = "elliptical";
    public static final String ERGOMETER = "ergometer";
    public static final String ESCALATOR = "escalator";
    public static final String EXTRA_STATUS = "actionStatus";
    public static final String FENCING = "fencing";
    public static final String FOOTBALL_AMERICAN = "football.american";
    public static final String FOOTBALL_AUSTRALIAN = "football.australian";
    public static final String FOOTBALL_SOCCER = "football.soccer";
    public static final String FRISBEE_DISC = "frisbee_disc";
    public static final String GARDENING = "gardening";
    public static final String GOLF = "golf";
    public static final String GYMNASTICS = "gymnastics";
    public static final String HANDBALL = "handball";
    public static final String HIGH_INTENSITY_INTERVAL_TRAINING = "interval_training.high_intensity";
    public static final String HIKING = "hiking";
    public static final String HOCKEY = "hockey";
    public static final String HORSEBACK_RIDING = "horseback_riding";
    public static final String HOUSEWORK = "housework";
    public static final String ICE_SKATING = "ice_skating";
    public static final String INTERVAL_TRAINING = "interval_training";
    public static final String IN_VEHICLE = "in_vehicle";
    public static final String JUMP_ROPE = "jump_rope";
    public static final String KAYAKING = "kayaking";
    public static final String KETTLEBELL_TRAINING = "kettlebell_training";
    public static final String KICKBOXING = "kickboxing";
    public static final String KICK_SCOOTER = "kick_scooter";
    public static final String KITESURFING = "kitesurfing";
    public static final String MARTIAL_ARTS = "martial_arts";
    public static final String MEDITATION = "meditation";
    public static final String MIME_TYPE_PREFIX = "vnd.google.fitness.activity/";
    public static final String MIXED_MARTIAL_ARTS = "martial_arts.mixed";
    public static final String ON_FOOT = "on_foot";
    public static final String OTHER = "other";
    public static final String P90X = "p90x";
    public static final String PARAGLIDING = "paragliding";
    public static final String PILATES = "pilates";
    public static final String POLO = "polo";
    public static final String RACQUETBALL = "racquetball";
    public static final String ROCK_CLIMBING = "rock_climbing";
    public static final String ROWING = "rowing";
    public static final String ROWING_MACHINE = "rowing.machine";
    public static final String RUGBY = "rugby";
    public static final String RUNNING = "running";
    public static final String RUNNING_JOGGING = "running.jogging";
    public static final String RUNNING_SAND = "running.sand";
    public static final String RUNNING_TREADMILL = "running.treadmill";
    public static final String SAILING = "sailing";
    public static final String SCUBA_DIVING = "scuba_diving";
    public static final String SKATEBOARDING = "skateboarding";
    public static final String SKATING = "skating";
    public static final String SKATING_CROSS = "skating.cross";
    public static final String SKATING_INDOOR = "skating.indoor";
    public static final String SKATING_INLINE = "skating.inline";
    public static final String SKIING = "skiing";
    public static final String SKIING_BACK_COUNTRY = "skiing.back_country";
    public static final String SKIING_CROSS_COUNTRY = "skiing.cross_country";
    public static final String SKIING_DOWNHILL = "skiing.downhill";
    public static final String SKIING_KITE = "skiing.kite";
    public static final String SKIING_ROLLER = "skiing.roller";
    public static final String SLEDDING = "sledding";
    public static final String SLEEP = "sleep";
    public static final String SLEEP_AWAKE = "sleep.awake";
    public static final String SLEEP_DEEP = "sleep.deep";
    public static final String SLEEP_LIGHT = "sleep.light";
    public static final String SLEEP_REM = "sleep.rem";
    public static final String SNOWBOARDING = "snowboarding";
    public static final String SNOWMOBILE = "snowmobile";
    public static final String SNOWSHOEING = "snowshoeing";
    public static final String SQUASH = "squash";
    public static final String STAIR_CLIMBING = "stair_climbing";
    public static final String STAIR_CLIMBING_MACHINE = "stair_climbing.machine";
    public static final String STANDUP_PADDLEBOARDING = "standup_paddleboarding";
    public static final String STATUS_ACTIVE = "ActiveActionStatus";
    public static final String STATUS_COMPLETED = "CompletedActionStatus";
    public static final String STILL = "still";
    public static final String STRENGTH_TRAINING = "strength_training";
    public static final String SURFING = "surfing";
    public static final String SWIMMING = "swimming";
    public static final String SWIMMING_OPEN_WATER = "swimming.open_water";
    public static final String SWIMMING_POOL = "swimming.pool";
    public static final String TABLE_TENNIS = "table_tennis";
    public static final String TEAM_SPORTS = "team_sports";
    public static final String TENNIS = "tennis";
    public static final String TILTING = "tilting";
    public static final String TREADMILL = "treadmill";
    public static final String UNKNOWN = "unknown";
    public static final String VOLLEYBALL = "volleyball";
    public static final String VOLLEYBALL_BEACH = "volleyball.beach";
    public static final String VOLLEYBALL_INDOOR = "volleyball.indoor";
    public static final String WAKEBOARDING = "wakeboarding";
    public static final String WALKING = "walking";
    public static final String WALKING_FITNESS = "walking.fitness";
    public static final String WALKING_NORDIC = "walking.nordic";
    public static final String WALKING_STROLLER = "walking.stroller";
    public static final String WALKING_TREADMILL = "walking.treadmill";
    public static final String WATER_POLO = "water_polo";
    public static final String WEIGHTLIFTING = "weightlifting";
    public static final String WHEELCHAIR = "wheelchair";
    public static final String WINDSURFING = "windsurfing";
    public static final String YOGA = "yoga";
    public static final String ZUMBA = "zumba";
    private static final String[] zzaQH;

    static {
        zzaQH = new String[120];
        zzaQH[9] = AEROBICS;
        zzaQH[119] = ARCHERY;
        zzaQH[10] = BADMINTON;
        zzaQH[11] = BASEBALL;
        zzaQH[12] = BASKETBALL;
        zzaQH[13] = BIATHLON;
        zzaQH[1] = BIKING;
        zzaQH[14] = BIKING_HAND;
        zzaQH[15] = BIKING_MOUNTAIN;
        zzaQH[16] = BIKING_ROAD;
        zzaQH[17] = BIKING_SPINNING;
        zzaQH[18] = BIKING_STATIONARY;
        zzaQH[19] = BIKING_UTILITY;
        zzaQH[20] = BOXING;
        zzaQH[21] = CALISTHENICS;
        zzaQH[22] = CIRCUIT_TRAINING;
        zzaQH[23] = CRICKET;
        zzaQH[C0394R.styleable.AppCompatTheme_switchStyle] = CROSSFIT;
        zzaQH[C0394R.styleable.AppCompatTheme_editTextStyle] = CURLING;
        zzaQH[24] = DANCING;
        zzaQH[Quests.SELECT_ENDING_SOON] = DIVING;
        zzaQH[117] = ELEVATOR;
        zzaQH[25] = ELLIPTICAL;
        zzaQH[Quests.SELECT_RECENTLY_FAILED] = ERGOMETER;
        zzaQH[118] = ESCALATOR;
        zzaQH[6] = "exiting_vehicle";
        zzaQH[26] = FENCING;
        zzaQH[27] = FOOTBALL_AMERICAN;
        zzaQH[28] = FOOTBALL_AUSTRALIAN;
        zzaQH[29] = FOOTBALL_SOCCER;
        zzaQH[30] = FRISBEE_DISC;
        zzaQH[31] = GARDENING;
        zzaQH[32] = GOLF;
        zzaQH[33] = GYMNASTICS;
        zzaQH[34] = HANDBALL;
        zzaQH[C0394R.styleable.AppCompatTheme_listMenuViewStyle] = HIGH_INTENSITY_INTERVAL_TRAINING;
        zzaQH[35] = HIKING;
        zzaQH[36] = HOCKEY;
        zzaQH[37] = HORSEBACK_RIDING;
        zzaQH[38] = HOUSEWORK;
        zzaQH[C0394R.styleable.AppCompatTheme_checkboxStyle] = ICE_SKATING;
        zzaQH[0] = IN_VEHICLE;
        zzaQH[115] = INTERVAL_TRAINING;
        zzaQH[39] = JUMP_ROPE;
        zzaQH[40] = KAYAKING;
        zzaQH[41] = KETTLEBELL_TRAINING;
        zzaQH[C0394R.styleable.AppCompatTheme_radioButtonStyle] = KICK_SCOOTER;
        zzaQH[42] = KICKBOXING;
        zzaQH[43] = KITESURFING;
        zzaQH[44] = MARTIAL_ARTS;
        zzaQH[45] = MEDITATION;
        zzaQH[46] = MIXED_MARTIAL_ARTS;
        zzaQH[2] = ON_FOOT;
        zzaQH[C0394R.styleable.AppCompatTheme_ratingBarStyle] = OTHER;
        zzaQH[47] = P90X;
        zzaQH[48] = PARAGLIDING;
        zzaQH[49] = PILATES;
        zzaQH[50] = POLO;
        zzaQH[51] = RACQUETBALL;
        zzaQH[52] = ROCK_CLIMBING;
        zzaQH[53] = ROWING;
        zzaQH[54] = ROWING_MACHINE;
        zzaQH[55] = RUGBY;
        zzaQH[8] = RUNNING;
        zzaQH[56] = RUNNING_JOGGING;
        zzaQH[57] = RUNNING_SAND;
        zzaQH[58] = RUNNING_TREADMILL;
        zzaQH[59] = SAILING;
        zzaQH[60] = SCUBA_DIVING;
        zzaQH[61] = SKATEBOARDING;
        zzaQH[62] = SKATING;
        zzaQH[63] = SKATING_CROSS;
        zzaQH[C0394R.styleable.AppCompatTheme_checkedTextViewStyle] = SKATING_INDOOR;
        zzaQH[64] = SKATING_INLINE;
        zzaQH[65] = SKIING;
        zzaQH[66] = SKIING_BACK_COUNTRY;
        zzaQH[67] = SKIING_CROSS_COUNTRY;
        zzaQH[68] = SKIING_DOWNHILL;
        zzaQH[69] = SKIING_KITE;
        zzaQH[70] = SKIING_ROLLER;
        zzaQH[71] = SLEDDING;
        zzaQH[72] = SLEEP;
        zzaQH[C0394R.styleable.AppCompatTheme_ratingBarStyleIndicator] = SLEEP_LIGHT;
        zzaQH[C0394R.styleable.AppCompatTheme_ratingBarStyleSmall] = SLEEP_DEEP;
        zzaQH[C0394R.styleable.AppCompatTheme_seekBarStyle] = SLEEP_REM;
        zzaQH[C0394R.styleable.AppCompatTheme_spinnerStyle] = SLEEP_AWAKE;
        zzaQH[73] = SNOWBOARDING;
        zzaQH[74] = SNOWMOBILE;
        zzaQH[75] = SNOWSHOEING;
        zzaQH[76] = SQUASH;
        zzaQH[77] = STAIR_CLIMBING;
        zzaQH[78] = STAIR_CLIMBING_MACHINE;
        zzaQH[79] = STANDUP_PADDLEBOARDING;
        zzaQH[3] = STILL;
        zzaQH[80] = STRENGTH_TRAINING;
        zzaQH[81] = SURFING;
        zzaQH[82] = SWIMMING;
        zzaQH[83] = SWIMMING_POOL;
        zzaQH[84] = SWIMMING_OPEN_WATER;
        zzaQH[85] = TABLE_TENNIS;
        zzaQH[86] = TEAM_SPORTS;
        zzaQH[87] = TENNIS;
        zzaQH[5] = TILTING;
        zzaQH[88] = TREADMILL;
        zzaQH[4] = UNKNOWN;
        zzaQH[89] = VOLLEYBALL;
        zzaQH[90] = VOLLEYBALL_BEACH;
        zzaQH[91] = VOLLEYBALL_INDOOR;
        zzaQH[92] = WAKEBOARDING;
        zzaQH[7] = WALKING;
        zzaQH[93] = WALKING_FITNESS;
        zzaQH[94] = WALKING_NORDIC;
        zzaQH[95] = WALKING_TREADMILL;
        zzaQH[116] = WALKING_STROLLER;
        zzaQH[96] = WATER_POLO;
        zzaQH[97] = WEIGHTLIFTING;
        zzaQH[98] = WHEELCHAIR;
        zzaQH[99] = WINDSURFING;
        zzaQH[100] = YOGA;
        zzaQH[Quests.SELECT_COMPLETED_UNCLAIMED] = ZUMBA;
    }

    FitnessActivities() {
    }

    public static String getMimeType(String str) {
        String valueOf = String.valueOf(MIME_TYPE_PREFIX);
        String valueOf2 = String.valueOf(str);
        return valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
    }

    public static String getName(int i) {
        if (i < 0 || i >= zzaQH.length) {
            return UNKNOWN;
        }
        String str = zzaQH[i];
        return str == null ? UNKNOWN : str;
    }

    public static int zzdY(String str) {
        for (int i = 0; i < zzaQH.length; i++) {
            if (zzaQH[i].equals(str)) {
                return i;
            }
        }
        return 4;
    }
}
